// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'diagram': string;
  'flowWrapper': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
